import "./App.css";
import React from "react";
import { Switch, BrowserRouter as Router, Route } from "react-router-dom";
import Checkup from "./components/Checkup"
import Medicines from "./components/Medicines"
import IPhone678Plus1 from "./components/IPhone678Plus1";
import DAILYDAIRYIcon from "./components/DAILYDAIRYIcon";
import HealthTipsIcon from "./components/HealthTipsIcon";
import MenuIcon from "./components/MenuIcon";
import HealthManagement from "./components/HealthManagement";
import MedicineReminder from "./components/MedicineReminder";

function App() {
  return (
    <Router>
      <Switch>
      <Route path="/Checkup">
          <Checkup {...iPhone678Plus1Data} />
        </Route>
        <Route path="/Medicines">
          <Medicines {...iPhone678Plus1Data} />
        </Route>
        <Route path="/:path(|iphone-6-7-8-plus-1)">
          <IPhone678Plus1 {...iPhone678Plus1Data} />
        </Route>
        <Route path="/daily-dairy-icon">
          <DAILYDAIRYIcon {...dAILYDAIRYIconData} />
        </Route>
        <Route path="/health-tips-icon">
          <HealthTipsIcon {...healthTipsIconData} />
        </Route>
        <Route path="/menu-icon">
          <MenuIcon {...menuIconData} />
        </Route>
        <Route path="/health-management">
          <HealthManagement
            iconAwesomeArrowLeft="/img/icon-awesome-arrow-left@1x.png"
            buyNowForRs0Only="BUY NOW FOR RS-0 ONLY"
            path90="/img/path-90@1x.png"
            path91="/img/path-91@1x.png"
            requestACallback="REQUEST A CALLBACK"
            iconCall="/img/icon-feather-phone-call@1x.png"
            path88="/img/path-88-1@1x.png"
          />
        </Route>
        <Route path="/medicine-reminder">
          <MedicineReminder {...medicineReminderData} />
        </Route>
      </Switch>
    </Router>
  );
}

export default App;
const group71Data = {
    path26: "/img/path-26@1x.png",
};

const group8Data = {
    path26: "/img/d4-removebg-preview-1@1x.png",
    group7Props: group71Data,
};

const iPhone678Plus1Data = {
    tip: "/img/tip@1x.png",
    percent: "100%",
    iconBluetooth: "/img/bluetooth@1x.png",
    wiFiFull: "/img/carrot@1x.png",
    iconSignal: "/img/wi-fi-full@1x.png",
    iconBar_Chart: "/img/cellular-connection@1x.png",
    ripudamanSingh: "Ripudaman Singh",
    price: "R",
    path6: "/img/path-6@1x.png",
    path7: "/img/path-7@1x.png",
    path8: "/img/path-8@1x.png",
    path9: "/img/path-9@1x.png",
    iconCart: "/img/path-10@1x.png",
    searchForDoctors: "Search for doctors",
    iconFeatherSearch: "/img/path-11@1x.png",
    path12: "/img/path-12@1x.png",
    dairy: "/img/mask-group-1@1x.png",
    trackYourVitals1: <React.Fragment>Track your vitals &amp;<br />medical records with</React.Fragment>,
    title: "Digital Diary",
    explore1: "EXPLORE",
    iconOpenArrowRight1: "/img/icon-open-arrow-right@1x.png",
    medicalBookD: "/img/medical-book--d@1x.png",
    maskGroup11: "/img/mask-group-1-1@1x.png",
    neverMissOutOnAnyDoseWith: <React.Fragment>Never miss out<br />on any dose with</React.Fragment>,
    medicineReminders1: <React.Fragment>Medicine<br />Reminders</React.Fragment>,
    explore2: "EXPLORE",
    iconOpenArrowRight2: "/img/icon-open-arrow-right-1@1x.png",
    isolated3DAlarmClockIcon_4391851224: "/img/isolated-3d-alarm-clock-icon-439185-12242-removebg-preview@1x.png",
    maskGroup12: "/img/mask-group-1-2@1x.png",
    explore3: "/img/path-80@1x.png",
    explore4: "EXPLORE",
    beautifulSmilingGirlUsingMobilePhon: "/img/beautiful-smiling-girl-using-mobile-phone-looking-smartphone-ple@1x.png",
    healthManagementMadeEasyFor: <React.Fragment>Health management<br />made easy for</React.Fragment>,
    bpSugarControl: "BP & Sugar Control",
    maskGroup13: "/img/mask-group-1-1@1x.png",
    explore5: "EXPLORE",
    x25Off: "25% Off",
    onAllPrescribedMedicines: <React.Fragment>On all prescribed<br />medicines</React.Fragment>,
    medicine1: "/img/medicine-1@1x.png",
    maskGroup14: "/img/mask-group-1-1@1x.png",
    explore6: "/img/path-81@1x.png",
    explore7: "EXPLORE",
    x20Off: "20% Off",
    onAllYourHealthDevices: <React.Fragment>On all your Health<br />Devices</React.Fragment>,
    watch: "/img/watch@1x.png",
    tCApply: "T&C apply",
    maskGroup15: "/img/mask-group-1-2@1x.png",
    explore8: "EXPLORE",
    x40Off: "40% Off",
    onAllYourHealthWellnessProducts: <React.Fragment>On all your Health<br />&amp; Wellness Products</React.Fragment>,
    herbal1: "/img/herbal-1@1x.png",
    findADoctorNearYou: "Find a Doctor Near You",
    x25OffOnConsultations: "25% OFF ON CONSULTATIONS",
    iconIonicIosArrowDroprightCircle: "/img/icon-ionic-ios-arrow-dropright-circle@1x.png",
    maskGroup2: "/img/mask-group-2@1x.png",
    upto81Off: "UPTO 81% OFF",
    labTest: "Lab Test",
    chemicalFlask: "/img/chemical-flask@1x.png",
    meater: "/img/meater@1x.png",
    upto50Off: "UPTO 50% OFF",
    healthDevices: <React.Fragment>Health<br />Devices</React.Fragment>,
    bpSugarPrograms: <React.Fragment>BP &amp; Sugar<br />Programs</React.Fragment>,
    heartRate: "/img/heart-rate@1x.png",
    medicine2: "/img/medicine@1x.png",
    upto30Off: "UPTO 30% OFF",
    medicines: "Medicines",
    upto35Off: "UPTO 35% OFF",
    healthWellness: <React.Fragment>Health &amp;<br />Wellness</React.Fragment>,
    herbal2: "/img/herbal@1x.png",
    healthCover: "Health Cover",
    peopleWearingMask: "/img/people-wearing-mask@1x.png",
    onAllHealthDevices: <React.Fragment>on all health<br />devices</React.Fragment>,
    extra15Cashback: <React.Fragment>Extra 15%<br />cashback</React.Fragment>,
    health_DevicesRemovebgPreview1: "/img/health-devices-removebg-preview-1@1x.png",
    pHAB15: "P H A B 1 5",
    flat10Off10Cashback: <React.Fragment>FLAT 10% OFF<br />+10% Cashback</React.Fragment>,
    berriesMix250G1800X1007RemovebgPrev1: "/img/berries-mix-250g-1-800x1007-removebg-preview@1x.png",
    berriesMix250G1800X1007RemovebgPrev2: "/img/berries-mix-250g-1-800x1007-removebg-preview-1@1x.png",
    onOrdersAboveRs399: "on orders above Rs-399",
    path29: "/img/path-29@1x.png",
    discount: "DISCOUNT",
    path30: "/img/path-30@1x.png",
    useCodeSep20: "Use code: SEP20",
    offersForYou: "Offers for you",
    saveExtraOnYourHealthExpenses: <React.Fragment>Save extra on your health<br />expenses!</React.Fragment>,
    spanText1: "Starting from",
    spanText2: "    ",
    spanText3: "   49 only",
    iconAwesomeRupeeSign1: "/img/icon-awesome-rupee-sign@1x.png",
    startSavingNow: "START SAVING NOW",
    path22: "/img/path-22@1x.png",
    path23: "/img/path-23@1x.png",
    medoseLogoFinalPng: "/img/medose-logo-final-png@1x.png",
    flat50Off: "Flat 50% Off",
    x10Cashback: "+10% cashback",
    cARE25: "C A R E 2 5",
    handHoldsMedicineCapsulesIconSignSy: "/img/hand-holds-medicine-capsules-icon-sign-symbol-blue-background-3d@1x.png",
    onetouchDevices: <React.Fragment>OneTouch<br />Devices</React.Fragment>,
    flat10Cashback: <React.Fragment>Flat 10% <br />cashback</React.Fragment>,
    health_DevicesRemovebgPreview2: "/img/health-devices-removebg-preview@1x.png",
    startYourJourneyT: <React.Fragment>Start your journey<br />towards a healthy life.</React.Fragment>,
    trackYourVitals2: "Track your vitals",
    convertPrescriptionsToReminders: <React.Fragment>Convert Prescriptions<br />to Reminders</React.Fragment>,
    medicineReminders2: "Medicine reminders",
    medicalReport1: "/img/medical-report--1-@1x.png",
    tracker: "/img/tracker@1x.png",
    reminder: "/img/reminder@1x.png",
    andMuchMore: "and much more",
    doctor: "/img/doctor-1@1x.png",
    letSGetStarted: "LET'S GET STARTED",
    path241: "/img/path-24@1x.png",
    path251: "/img/path-25@1x.png",
    x4154153777_GoogleSearch3DModelChar: "/img/415-4153777-google-search-3d-model-character-boy-character-chara@1x.png",
    findSpecialistsBySymptoms: "Find Specialists By Symptoms",
    pimplesRemovebgPreview: "/img/pimples-removebg-preview@1x.png",
    high_And_Low_BpRemovebgPreview: "/img/high-and-low-bp-removebg-preview@1x.png",
    human_HearytRemovebgPreview: "/img/human-hearyt-removebg-preview@1x.png",
    pimpleAcne: "Pimple/Acne",
    highLowBloodSugar: <React.Fragment>High/ Low Blood<br />Sugar</React.Fragment>,
    fastHeartbeat: "Fast Heartbeat",
    womanFeelChestPain53146724432127Rem: "/img/woman-feel-chest-pain-5314672-4432127-removebg-preview@1x.png",
    healthcare: "/img/healthcare@1x.png",
    downloadRemovebgPreview: "/img/download-removebg-preview@1x.png",
    littleBoySufferingFromSoreThroatTou: "/img/little-boy-suffering-from-sore-throat-touching-his-painful-neck-@1x.png",
    downloadRemovebgPreview1: "/img/download-removebg-preview--1-@1x.png",
    cough1: "/img/cough@1x.png",
    headache1: "/img/headache@1x.png",
    chestPain: "Chest Pain",
    highLowBloodPressure: <React.Fragment>High/Low Blood<br /> Pressure</React.Fragment>,
    pcos: "PCOS",
    soreThroat: "Sore throat",
    hairLoss: "Hair Loss",
    cough2: "Cough",
    headache2: "Headache",
    findASpecialist: "FIND A SPECIALIST",
    path242: "/img/path-24-1@1x.png",
    path252: "/img/path-25-1@1x.png",
    referAndEarn: "Refer And Earn",
    inviteFriendsAndF: <React.Fragment>Invite friends and family<br />to Phable and earn upto</React.Fragment>,
    number: "500",
    iconAwesomeRupeeSign2: "/img/icon-awesome-rupee-sign-1@1x.png",
    earningRemovebgPreview: "/img/earning-removebg-preview@1x.png",
    earnRs500Now: "EARN RS.500 NOW",
    path243: "/img/path-24-1@1x.png",
    path253: "/img/path-25-1@1x.png",
    assessYourHealthScore: "Assess Your Health score",
    spanText4: <React.Fragment>Predict your<br />risk of getting<br /></React.Fragment>,
    spanText5: <React.Fragment>Kidney<br />Disease.</React.Fragment>,
    diabetes1: "/img/diabetes@1x.png",
    spanText6: <React.Fragment>Assess<br />your risk of<br /></React.Fragment>,
    spanText7: <React.Fragment>developing<br />diabetes.</React.Fragment>,
    diabetes2: "/img/diabetes-1@1x.png",
    spanText8: <React.Fragment>Assess your<br /></React.Fragment>,
    spanText9: <React.Fragment>mental <br />Wellness<br /></React.Fragment>,
    spanText10: "score",
    diabetes3: "/img/diabetes-2@1x.png",
    diabetes4: "/img/diabetes-3@1x.png",
    spanText11: <React.Fragment>Feeling<br /></React.Fragment>,
    spanText12: <React.Fragment>Anxious?<br /></React.Fragment>,
    spanText13: <React.Fragment>Here is a<br />solution</React.Fragment>,
    exploreAllRiskAssessments1: "EXPLORE ALL RISK ASSESSMENTS",
    path244: "/img/path-24-1@1x.png",
    path254: "/img/path-25-1@1x.png",
    exploreAllRiskAssessments2: "EXPLORE ALL RISK ASSESSMENTS",
    path245: "/img/path-24-1@1x.png",
    path255: "/img/path-25-1@1x.png",
    healthTips1: "Health Tips",
    tablet1: "/img/tablet--1-@1x.png",
    overlapGroup1: "/img/path-65@1x.png",
    canAlprazolamHelpDepression: "Can alprazolam help depression?",
    alprazolamCommonly: <React.Fragment>Alprazolam commonly known as Xanas<br />is usually used to treat anxiety and panic<br />disorders. It is not given to those with depre….</React.Fragment>,
    address1: "08 Sep 2022",
    iconHeart: "/img/icon-ionic-ios-heart-empty-1@1x.png",
    path26: "/img/path-26-1@1x.png",
    path27: "/img/path-27-1@1x.png",
    iconBookmark: "/img/path-28-1@1x.png",
    address2: "1354 Likes",
    address3: "401 Shares",
    save: "Save",
    overlapGroup27: "/img/union-2@1x.png",
    iconHome: "/img/icon-material-home@1x.png",
    place: "Home",
    path17: "/img/path-17-1@1x.png",
    path18: "/img/path-18-1@1x.png",
    diary: "Diary",
    iconLight_Bulb: "/img/icon-material-lightbulb-outline-1@1x.png",
    healthTips2: "Health Tips",
    iconMetroMenu: "/img/icon-metro-menu-2@1x.png",
    menu: "Menu",
    group8Props: group8Data,
};

const aROW2Data = {
    className: "arow-1",
};

const iconFeatherBook1Data = {
    path17: "/img/path-17-2@1x.png",
    path18: "/img/path-18-2@1x.png",
};

const bloodGlucose1Data = {
    bloodGlucose: "Blood Glucose",
    x57OfAdultsInInd: <React.Fragment>57% of adults in India live with diabetes but are <br />undiagnosed Monitor regularly</React.Fragment>,
    glucoseMeter: "/img/glucose-meter@1x.png",
};

const bloodGlucose2Data = {
    bloodGlucose: "Blood Pressure",
    x57OfAdultsInInd: <React.Fragment>70% hypertensive people in India are unaware of<br />their condition. Check your BP</React.Fragment>,
    glucoseMeter: "/img/blood-pressure@1x.png",
    className: "blood-pressure",
};

const bloodGlucose3Data = {
    bloodGlucose: "Heart Rate",
    x57OfAdultsInInd: <React.Fragment>Heart rate is an indicator of overall health. Monitor<br />heart rate every once in a while.</React.Fragment>,
    glucoseMeter: "/img/heart-rate-1@1x.png",
    className: "heart-rate-1",
};

const dAILYDAIRYIconData = {
    iconIonicMdArrowBack: "/img/icon-ionic-md-arrow-back-1@1x.png",
    digitalDiary: "Digital Diary",
    overlapGroup: "/img/path-66-1@1x.png",
    path67: "/img/path-67-1@1x.png",
    path68: "/img/path-68-3@1x.png",
    path69: "/img/path-69-3@1x.png",
    x4154153777_GoogleSearch3DModelChar: "/img/415-4153777-google-search-3d-model-character-boy-character-chara-2@1x.png",
    myHealth: "My Health",
    activity: "Activity",
    connectYourDevices: "Connect your Devices",
    toRecordYourVitalsWithEase: "to record your vitals with ease",
    iconIonicIosArrowBack1: "/img/icon-ionic-ios-arrow-back-2@1x.png",
    spanText1: "Upload ",
    spanText2: <React.Fragment>your<br />health reports</React.Fragment>,
    pathContainer: "/img/path-70@1x.png",
    path74: "/img/path-74@1x.png",
    path72: "/img/path-72@1x.png",
    path73: "/img/path-72@1x.png",
    iconIonicIosFunnel: "/img/icon-ionic-ios-funnel@1x.png",
    spanText3: "Share ",
    spanText4: <React.Fragment>health data <br />with your doctor</React.Fragment>,
    path75: "/img/path-75@1x.png",
    path76: "/img/path-76@1x.png",
    path77: "/img/path-77@1x.png",
    path78: "/img/path-78@1x.png",
    path79: "/img/path-79@1x.png",
    freeHealthAssessments: "Free Health Assessments",
    diabetes11: "/img/diabetes--1-@1x.png",
    diabetes: "Diabetes",
    thisToolIsASimpl1: <React.Fragment>This tool is a<br />simple screening<br />algorithm that<br />helps predict.</React.Fragment>,
    iconIonicIosArrowBack2: "/img/icon-ionic-ios-arrow-back-5@1x.png",
    diabetes12: "/img/diabetes--1--1@1x.png",
    depression: "Depression",
    takeThisPhq9Depr: <React.Fragment>Take this PHQ-9<br />depression<br />self-test to<br />assess whether</React.Fragment>,
    iconIonicIosArrowBack3: "/img/icon-ionic-ios-arrow-back-5@1x.png",
    diabetes13: "/img/diabetes--1--2@1x.png",
    chronicKidney: "Chronic Kidney",
    iconIonicIosArrowBack4: "/img/icon-ionic-ios-arrow-back-5@1x.png",
    thisToolIsASimpl2: <React.Fragment>This tool is a<br />simple screening<br />algorithm that<br />helps predict.</React.Fragment>,
    diabetes14: "/img/diabetes--1--3@1x.png",
    spanText5: "A",
    spanText6: "nxiety",
    iconIonicIosArrowBack5: "/img/icon-ionic-ios-arrow-back-5@1x.png",
    thisToolIsASimpl3: <React.Fragment>This tool is a<br />simple screening<br />algorithm that<br />helps predict.</React.Fragment>,
    diabetes15: "/img/diabetes--1--4@1x.png",
    heartDisease: "Heart Disease",
    iconIonicIosArrowBack6: "/img/icon-ionic-ios-arrow-back-5@1x.png",
    thisToolIsUsedTo: <React.Fragment>This tool is used<br />to estimate the<br />10 year risk of <br />developing a heart</React.Fragment>,
    myHealthCharts: "My Health Charts",
    overlapGroup6: "/img/union-2-1-1x-png@1x.png",
    iconHome: "/img/icon-material-home-1@1x.png",
    place: "Home",
    diary: "Diary",
    iconLight_Bulb: "/img/icon-material-lightbulb-outline-1@1x.png",
    healthTips: "Health Tips",
    iconMetroMenu: "/img/icon-metro-menu-2@1x.png",
    menu: "Menu",
    aROWProps: aROW2Data,
    iconFeatherBookProps: iconFeatherBook1Data,
    bloodGlucose1Props: bloodGlucose1Data,
    bloodGlucose2Props: bloodGlucose2Data,
    bloodGlucose3Props: bloodGlucose3Data,
};

const group72Data = {
    path26: "/img/path-26-1@1x.png",
    className: "group-7-1",
};

const iconFeatherBook2Data = {
    path17: "/img/path-17-1@1x.png",
    path18: "/img/path-18-1@1x.png",
};

const healthTipsIconData = {
    iconIonicMdArrowBack: "/img/icon-ionic-md-arrow-back-1@1x.png",
    price: "ALL",
    saved: "SAVED",
    covid19: "COVID-19",
    advancement: "ADVANCEMENT",
    diet: "DIET",
    exercise: "EXERCISE",
    medicines: "MEDICINES",
    sleepAndRelaxation: "SLEEP AND RELAXATION",
    awarness: "AWARNESS",
    lifestyle: "LIFESTYLE",
    selfCare: "SELF CARE",
    healthTips1: "Health Tips",
    d4RemovebgPreview: "/img/d4-removebg-preview-1@1x.png",
    d_1RemovebgPreview: "/img/d-1-removebg-preview-1@1x.png",
    d2RemovebgPreview: "/img/d2-removebg-preview-1@1x.png",
    d3RemovebgPreview: "/img/d3-removebg-preview-1@1x.png",
    schizophrenia: "SCHIZOPHRENIA",
    depression: "DEPRESSION",
    anxietyDisorder: "ANXIETY DISORDER",
    postTraumaticStress: "POST-TRAUMATIC STRESS",
    overlapGroup12: "/img/union-2-1-1x-png@1x.png",
    iconHome: "/img/icon-material-home-1@1x.png",
    place: "Home",
    diary: "Diary",
    iconLight_Bulb: "/img/icon-material-lightbulb-outline-3@1x.png",
    healthTips2: "Health Tips",
    iconMetroMenu: "/img/icon-metro-menu-2@1x.png",
    menu: "Menu",
    overlapGroup1: "/img/path-65-1@1x.png",
    canAlprazolamHelpDepression: "Can alprazolam help depression?",
    alprazolamCommonly: <React.Fragment>Alprazolam commonly known as Xanas<br />is usually used to treat anxiety and panic<br />disorders. It is not given to those with depre….</React.Fragment>,
    address1: "08 Sep 2022",
    iconHeart: "/img/icon-ionic-ios-heart-empty-1@1x.png",
    path26: "/img/path-26-1@1x.png",
    path27: "/img/path-27-1@1x.png",
    iconBookmark: "/img/path-28-1@1x.png",
    address2: "1354 Likes",
    address3: "401 Shares",
    save: "Save",
    tablet1: "/img/tablet--1--1@1x.png",
    group7Props: group72Data,
    iconFeatherBookProps: iconFeatherBook2Data,
};

const iconFeatherBook3Data = {
    path17: "/img/path-17-1@1x.png",
    path18: "/img/path-18-1@1x.png",
};

const aDD4Data = {
    className: "add-3",
};

const menuIconData = {
    overlapGroup10: "/img/union-2-1-1x-png@1x.png",
    iconHome: "/img/icon-material-home-1@1x.png",
    place: "Home",
    diary: "Diary",
    iconLight_Bulb: "/img/icon-material-lightbulb-outline-1@1x.png",
    healthTips: "Health Tips",
    iconMetroMenu: "/img/icon-metro-menu-1@1x.png",
    menu: "Menu",
    iconAwesomeCapsules: "/img/icon-awesome-capsules@1x.png",
    myPrescriptions: "My Prescriptions",
    myProfile: "My Profile",
    myReports: "My Reports",
    phableWallet: "Phable wallet",
    referEarn: "Refer & Earn",
    myDevices: "My Devices",
    myDoctors: "My Doctors",
    myAddresses: "My Addresses",
    myOrders: "My Orders",
    myRewards: "My Rewards",
    myConsultations: "My Consultations",
    iconFeatherMessageSquare: "/img/icon-feather-message-square@1x.png",
    pathContainer: "/img/path-55@1x.png",
    path56: "/img/path-56@1x.png",
    path57: "/img/path-57@1x.png",
    path46: "/img/path-46@1x.png",
    path47: "/img/path-47@1x.png",
    iconMaterialDeviceHub: "/img/icon-material-device-hub@1x.png",
    iconMaterialAccountCircle: "/img/icon-material-account-circle@1x.png",
    iconAwesomeAddressCard1: "/img/icon-awesome-address-card-1@1x.png",
    iconAwesomeWallet: "/img/icon-awesome-wallet@1x.png",
    overlapGroup2: "/img/path-35@1x.png",
    path37: "/img/path-37@1x.png",
    path38: "/img/path-37@1x.png",
    path36: "/img/path-36@1x.png",
    iconPlay: "/img/icon-ionic-ios-play-circle@1x.png",
    path60: "/img/path-60@1x.png",
    path61: "/img/path-61@1x.png",
    path62: "/img/path-62@1x.png",
    path63: "/img/path-63@1x.png",
    path64: "/img/path-64@1x.png",
    iconLock: "/img/icon-map-doctor@1x.png",
    userGuideVideo: "User Guide Video",
    path53: "/img/path-53@1x.png",
    path54: "/img/path-54@1x.png",
    messagesAlerts: "Messages/ Alerts",
    path41: "/img/path-41@1x.png",
    path42: "/img/path-42@1x.png",
    phable_LogoRemovebgPreviewPng: "/img/phable-logo-removebg-preview-png@1x.png",
    iconAwesomeAddressCard2: "/img/icon-awesome-address-card-1@1x.png",
    overlapGroup5: "/img/path-48@1x.png",
    path52: "/img/path-52@1x.png",
    path49: "/img/path-49@1x.png",
    path50: "/img/path-50@1x.png",
    path51: "/img/path-50@1x.png",
    path58: "/img/path-58@1x.png",
    path59: "/img/path-59@1x.png",
    settings: "Settings",
    contactPhable: "Contact Phable",
    termsConditions: "Terms & Conditions",
    privacyPolicy: "Privacy Policy",
    logout: "Logout",
    x4154153777_GoogleSearch3DModelChar: "/img/415-4153777-google-search-3d-model-character-boy-character-chara-1@1x.png",
    addAMember: "+    Add a Member",
    ripudamanSingh: "Ripudaman Singh",
    joinNow: "Join Now",
    name: "Max savings, max benefits",
    iconIonicIosArrowBack1: "/img/icon-ionic-ios-arrow-back@1x.png",
    iconIonicIosArrowBack2: "/img/icon-ionic-ios-arrow-back-1@1x.png",
    downloadRemovebgPreview31: "/img/download-removebg-preview--3---1-@1x.png",
    explorePrograms: "EXPLORE PROGRAMS",
    medoseLogoFinalPng: "/img/medose-logo-final-png-1@1x.png",
    iconFeatherBookProps: iconFeatherBook3Data,
    aDDProps: aDD4Data,
};

const medicineReminderData = {
    iconIonicMdArrowBack: "/img/icon-ionic-md-arrow-back-2@1x.png",
    digitalDiary: "Digital Diary",
    overlapGroup: "/img/path-66-1@1x.png",
    path67: "/img/path-67-1@1x.png",
    path68: "/img/path-68-3@1x.png",
    path69: "/img/path-69-3@1x.png",
    x4154153777_GoogleSearch3DModelChar: "/img/415-4153777-google-search-3d-model-character-boy-character-chara-3@1x.png",
    myHealth: "My Health",
    activity: "Activity",
    capsule: "/img/capsule@1x.png",
    spanText1: "Get Medicine Reminders In ",
    spanText2: <React.Fragment>Just<br /></React.Fragment>,
    spanText3: "two steps",
    x1UploadYourPresc: <React.Fragment>1. Upload your Prescription<br />2. We will create reminders.</React.Fragment>,
    group12: "/img/path-89@1x.png",
    path82: "/img/path-82@1x.png",
    path83: "/img/path-83@1x.png",
    path84: "/img/path-84@1x.png",
    uploadPrescription: "UPLOAD PRESCRIPTION",
    or: "OR",
    setRemindersManually: "Set reminders manually",
    clickHereToGetReminders: "Click here to get reminders",
    path85: "/img/path-85@1x.png",
    path86: "/img/path-86@1x.png",
    path87: "/img/path-87@1x.png",
    path88: "/img/path-88-1@1x.png",
};

